# line-length = 150 # Used by E501 (pycodestyle)

[lint]
select = [
    "E", # pycodestyle
    "W", # pycodestyle
    "C4", # https://docs.astral.sh/ruff/rules/#flake8-comprehensions-c4
    "SIM",
    "TCH", # https://docs.astral.sh/ruff/rules/#flake8-type-checking-tch
]
ignore = [
    "E501", # Ignore line length
]

[lint.flake8-type-checking]
# Add quotes around type annotations, if doing so would allow
# an import to be moved into a type-checking block.
quote-annotations = true
